nelmio_api_doc:
    documentation:
        info:
            title: BusApp API
            description: Esta es la RESTful API de BusApp
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc